version: '3.8'

services:
  webapp:
    image: jukebox
    command: ["uvicorn", "jukebox.main:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      DATABASE_URL: postgres://postgres:admin123@database:5432/jukebox
    volumes:
      - ./jukebox:/opt/jukebox
    depends_on:
      - migrate
      - database
    links:
      - database
    restart: on-failure
    deploy:
      replicas: 4

  nginx:
    image: nginx
    volumes:
      - ./misc/nginx/compose.conf:/etc/nginx/conf.d/compose.conf
    ports:
      - "8000:8000"
    depends_on:
      - webapp
    links:
      - webapp
    restart: on-failure

  scheduler:
    image: jukebox
    command: [ "python", "jukebox/scheduler.py" ]
    environment:
      DATABASE_URL: postgres://postgres:admin123@database:5432/jukebox
    volumes:
      - ./jukebox:/opt/jukebox
    depends_on:
      - database
      - webapp
    links:
      - database
    restart: on-failure

  migrate:
    image: jukebox
    command: ["python", "jukebox/database/migrations.py"]
    environment:
      DATABASE_URL: postgres://postgres:admin123@database:5432/jukebox
    volumes:
      - ./jukebox:/opt/jukebox
    depends_on:
      - database
    links:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: jukebox
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

volumes:
  pg_data: