[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "jukebox"
version = "0.0.0"  # placeholder
description = "A Music Recommendation System made using Flutter and backed by FastAPI."
authors = ["JukeBox Developers <arpan.mahanty.007@gmail.com>"]

[tool.poetry.dependencies]
# Server
fastapi = "^0.88.0"
uvicorn = { extras = ["standard"], version = "^0.20.0" }
gunicorn = "^20.1.0"

# Database
databases = { extras = ["asyncpg"], version = "^0.7.0" }
yoyo-migrations = "^8.2.0"

# Productivity
psutil = "^5.9.4"
pydantic = {extras = ["email"], version = "^1.10.2"}

# Others
python = "^3.10"
invoke = "^1.7.3"

[tool.poetry.group.dev.dependencies]
# Testing
pytest = "^7.2.0"
