[tool.poetry]
name = "jukebox"
version = "1.0.0"
description = "An Open Source Music Streaming App."
authors = ["JukeBox Developers <arpan.mahanty.007@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

fastapi = "^0.95.1"
uvicorn = { extras = ["standard"], version = "^0.21.1" }
gunicorn = "^20.1.0"
pydantic = { extras = ["email"], version = "^1.10.7" }
databases = { extras = ["asyncpg"], version = "^0.7.0" }
yoyo-migrations = "^8.2.0"
psycopg2-binary = "^2.9.6"
click = "^8.1.3"
psutil = "^5.9.5"
passlib = { extras = ["bcrypt"], version = "^1.7.4" }
python-jose = { extras = ["cryptography"], version = "^3.3.0" }


[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"
