[tool.poetry]
name = "jukebox"
version = "0.2.1"
description = "An Open Source Music Streaming App."
authors = ["JukeBox Developers <arpan.mahanty.007@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

fastapi = { version="^0.100.0b3", allow-prereleases = true }
uvicorn = "^0.22.0"
pydantic = { version = "^2.0.2", extras = ["email"] }
rocketry = "^2.5.1"
databases = { version = "^0.7.0", extras = ["asyncpg"] }
yoyo-migrations = "^8.2.0"
psycopg2-binary = "^2.9.6"
psutil = "^5.9.5"
pyyaml = "^6.0"
google-auth = "^2.21.0"

[tool.poetry.group.dev.dependencies]
watchfiles = "^0.19.0"

[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"
