[tool.poetry]
name = "jukebox"
version = "0.2.1"
description = "An Open Source Music Streaming App."
authors = ["JukeBox Developers <arpan.mahanty.007@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

fastapi = "^0.96.0"
rocketry = "^2.5.1"
uvicorn = "^0.22.0"
databases = { extras = ["asyncpg"], version = "^0.7.0" }
yoyo-migrations = "^8.2.0"
psycopg2-binary = "^2.9.6"
psutil = "^5.9.5"
pyyaml = "^6.0"
watchfiles = "^0.19.0"
google-auth = "^2.19.1"


[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"
