[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
    "poetry-core>=1.3.0"
]

[tool.poetry]
name = "projectxmusic"
version = "0.0.0"   # Used as placeholder only
description = "A Music Recommendation System made using Flutter and backed by FastAPI."
authors = [
    "Arpan Mahanty <arpan.mahanty.007@gmail.com>",
    "Apratim Sarkar <apratimsarkar13031999@gmail.com>",
]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.88.0"
gunicorn = "^20.1.0"
pyyaml = "^6.0"
uvicorn = { extras = ["standard"], version = "^0.20.0" }
passlib = { extras = ["bcrypt"], version = "^1.7.4" }
pylast = "^5.1.0"

[tool.poetry.group.test.dependencies]
pytest = "^7.2.0"
pytest-cov = "^4.0.0"

[tool.pytest.ini_options]
addopts = "--cov pxm --cov-report term:skip-covered"
testpaths = "tests"