[tool.poetry]
name = "jukebox"
version = "1.0.0"
description = "An Open Source Music Streaming App."
authors = ["JukeBox Developers <arpan.mahanty.007@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.92.0"
uvicorn = { extras = ["standard"], version = "^0.20.0" }
gunicorn = "^20.1.0"
pydantic = { extras = ["email"], version = "^1.10.5" }
psutil = "^5.9.4"
passlib = { extras = ["bcrypt"], version = "^1.7.4" }
python-jose = { extras = ["cryptography"], version = "^3.3.0" }
databases = {extras = ["asyncpg"], version = "^0.7.0"}
yoyo-migrations = "^8.2.0"
psycopg2-binary = "^2.9.5"


[tool.poetry.scripts]
runserver = "jukebox.tasks:run_server_task"
migrate = "jukebox.tasks:migrate_task"
makemigration = "jukebox.tasks:make_migration_task"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
