[tool.poetry]
name = "projectxmusic"
version = "0.0.0"   # Used as placeholder only
description = "A Music Recommendation System made using Flutter and backed by FastAPI."

# Copyrights and Licenses
license = "MIT"
authors = [
    "Arpan Mahanty <arpan.mahanty.007@gmail.com>",
    "Apratim Sarkar <apratimsarkar13031999@gmail.com>",
]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.85.1"
uvicorn = { extras = ["standard"], version = "^0.19.0" }
gunicorn = "^20.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
