# Header
name: Feature Request
description: Suggest an idea for this project
labels:
  - enhancement

# Body
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Request
      description: A clear and concise description of what the problem is
    validations:
      required: true
  - type: textarea
    id: feature-impact
    attributes:
      label: Possible Impact
      description: How much does this impact the user's experience by using this feature?
      placeholder: Not Applicable
  - type: textarea
    id: feature-reach
    attributes:
      label: Possible Reach
      description: The number of people that would be affected by this feature request
      placeholder: Not Applicable
