# Header
name: Other Issue
description: Anything Other than a New Feature or a Bug Report

# Body
body:
  - type: textarea
    id: description
    attributes:
      label: Other Issue
      description: A clear and concise description of what the issue is
    validations:
      required: true